### ISSUE TITLE
DCA disconnects when choosing certain templates

### ISSUE THREAD

**Issue by alyssa-acebedo** [Sage-Bionetworks/data_curator#190]
When testing this instance of the DCA https://shinypro.synapse.org/users/rchai/dc/, the app has disconnected a few times when choosing certain templates.

The app disconnects when choosing:

- Project: HTAPP, Folder: Clinical Therapy Colon, Template: Clinical Tier1 Therapy
- Project: HTAPP, Folder: single_cell_RNA_seq_level_2_colon, Template: scRNA-seq Level 2
- Project: HTAPP, Folder: single_cell_RNA_seq_level_3_colon, Template: scRNA-seq Level 3

**Comment by ychae** [comment]
Not sure if this is related, but in the current app (Sujay's version) the HTAPP/Vanderbilt centers have gotten disconnect errors for the following templates during generation and/or validation:

1. Vanderbilt single cell levels 1-3 (unable to generate templates) 
2. HTAPP MERFISH all levels (unable to generate or validate templates)
3. (and all of the tables in [this folder](https://drive.google.com/drive/folders/1vxF03IsnPWiTJyrwEENhfKGKxrXetLOu)- disconnect at submission) 

I think that third item's been addressed as well but please let me know if otherwise!

**Comment by rrchai** [comment]
```
Detailed traceback: 
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/models/metadata.py", line 306
, in populateModelManifest
    return mg.populate_manifest_spreadsheet(manifestPath, emptyManifestURL)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python
3.7/site-packages/schematic/manifest/generator.py", line 994, in populate_manifest_spreadsheet
    manifest_sh = self.set_dataframe_by_url(empty_manifest_url, manifest)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/manifest/generator.py", line 816, in set_dataframe_by_url
    wb.set_data_validation(start = start_col, end = end_col, condition_type = None)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/pygsheets/utils.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-pa [... truncated]
  76: <Anonymous>
```

here is the error raised by those templates mentioned in this ticket for `https://shinypro.synapse.org/users/rchai/dc/`

**Comment by rrchai** [comment]
Error using `schematic`:
 ```
populateModelManifest(
'HTAN Clinical Tier 1: Therapy', 
"/home/rchai/.synapseCache/362/75268362/synapse_storage_manifest.csv", 
"Therapy")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/models/metadata.py", line 306, in populateModelManifest
    return mg.populate_manifest_spreadsheet(manifestPath, emptyManifestURL)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/manifest/generator.py", line 994, in populate_manifest_spreadsheet
    manifest_sh = self.set_dataframe_by_url(empty_manifest_url, manifest)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/manifest/generator.py", line 816, in set_dataframe_by_url
    wb.set_data_validation(start = start_col, end = end_col, condition_type = None)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/pygsheets/utils.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/pygsheets/worksheet.py", line 1624, in set_data_validation
    grange = GridRange(worksheet=self, start=start, end=end)
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/pygsheets/address.py", line 245, in __init__
    self._apply_index_constraints()
  File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/pygsheets/address.py", line 417, in _apply_index_constraints
    assert self._start[1] <= self._end[1]
AssertionError

```

**Comment by ychae** [comment]
Update from Clarisse on Thursday 9/16:

I started making my way through the folder of outstanding HTAPP metadata tables, trying to submit them following the recent DCA fixes. I was able to submit a couple, but am still running into disconnect errors for many others. 

Would you be able to ask Rong if he can look into these? I'm linking below a few of the tables that failed (and where possible a successful table of the same type if that helps in the debugging process). 

**Biospecimen**

- Submitted: [PML](https://www.synapse.org/#!Synapse:syn26174519)
- Failed after clicking submit: [lung](https://drive.google.com/file/d/1Bo-nvFs6ZDjqaHd_bCmH2crcxnQ2KW7P/view?usp=sharing)
- Failed after clicking submit: [ovarian](https://drive.google.com/file/d/1DapQw9a62znpDxxMaCT5SfBdjXjUkatH/view?usp=sharing)

**ScRNAseq Level 1**

- Failed after clicking submit: [PML](https://drive.google.com/file/d/18B48uA_YevC6E7CK1LdBY06iPMLG6Cl5/view?usp=sharing)
- Failed after clicking submit: [sarcoma
](https://drive.google.com/file/d/1Ud5UKVgAAtrW146oBZdpYTcoHGAtFQwn/view?usp=sharing)

**Comment by milen-sage** [comment]
Reproduced - fix identified.
