### ISSUE TITLE
Validation on attributes with `list` rule causes app to crash

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#311]
**Describe the bug**
When trying to validate a manifest in the data curator app the app crashes and I get this error:

```
2022-04-05T23:09:41.297404+00:00 shinyapps[5727796]: Warning: Error in validationResult: object 'annotation_status' not found
2022-04-05T23:09:41.297516+00:00 shinyapps[5727796]:   13: fn
2022-04-05T23:09:41.297461+00:00 shinyapps[5727796]:   15: <Anonymous>
2022-04-05T23:09:41.297625+00:00 shinyapps[5727796]:    7: connect$retryingStartServer
2022-04-05T23:09:41.297664+00:00 shinyapps[5727796]:    6: eval
2022-04-05T23:09:41.297580+00:00 shinyapps[5727796]:    8: retry
2022-04-05T23:09:41.297712+00:00 shinyapps[5727796]:    5: eval

````

I tried to generate a new manifest in one of our demo projects and validate that and it worked fine, and I don’t see that other users have had this issue in our logs, so I am guessing it’s something to do with the contents of this manifest or the dataset I’m using…

It appears to happen when include annotations for this column in the manifest: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.csv#L406

**To Reproduce**
Alright, so I was able to come up with something reproducible: it happens whenever I try to annotate something that has a list validation rule. We have three attributes that have this rule: modelSystemName,tumorType and cellType. description of what the bug is.

1. Go to NF Data Curator App
2. Select a dataset, e.g. w/ genomics manifest
3. Fill in manifest, annotating modelSystemName,tumorType or cellType. 
4. Try to validate manifest 

**Expected behavior**
Validation should proceed, instead app crashes. 

**Environment**
This is using the app as built here: https://github.com/nf-osi/NF_data_curator/actions/runs/2001994081/workflow, with the develop version of schematic from 19 days ago, as well as the current version of develop through today (https://github.com/nf-osi/NF_data_curator/actions/runs/2099292364)

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Additional context**
slack here: https://sagebionetworks.slack.com/archives/C01ANC02U59/p1649197443845809
Might be related to #309 ?

**Comment by allaway** [comment]
Oops, accidentally closed with a commit...

**Comment by allaway** [comment]
I can confirm (using https://sagebio.shinyapps.io/NF_data_curator-staging/) that removing list validation patches this bug (but, of course, we want list validation :) )

**Comment by rrchai** [comment]
@allaway 
if you see this error: `Error in validationResult: object 'annotation_status' not found`, it is mostly likely because `validateModelManifest()`, [here](https://github.com/nf-osi/NF_data_curator/blob/c270d55edf530bca69b00848dd3e77a37295dfef/server.R#L287), from schematic failed running. I wonder if you run validation via schematic cli, would you see a bit more detailed errors?
```
>schematic model -c <path-to-schematic-config.yml> validate -mp <path-to-manifest> -dt <dataType>
```

> Might be related to https://github.com/Sage-Bionetworks/data_curator/issues/309 ?
I will have some updates to incorporate new changes from validation function from schematic, but the new changes from schematic has not been merged to `develop` of schematic yet. It might be another issue to crash the app in your case.

**Comment by allaway** [comment]
Thanks, Rong for the suggestion!
Oh yeah, good point, probably not related to #309 then. 

I created a mini manifest to reproduce my error: 
```
Filename,progressReportNumber,fileFormat,resourceType,dataType,dataSubtype,assay,individualID,sex,species,modelSystemName
Whole Exome Sequencing/hc5gydsx3_agaacctaca-gatatatggc_l001_r1.fastq.gz,6,fastq,experimentalData,genomicVariants,raw,Whole Exome Sequencing,UF17,Male,Homo sapiens,foo
```

And, with config that has this section:

```
model:
  input:
    location: '/Users/rallaway/desktop/temp/NF.jsonld'
    file_type: 'local'
```
  
I then created a fresh conda environment with the latest `develop` version of schematic. 

then  run: 

```(scheamtic) ➜  temp schematic model -c ~/Desktop/temp/config.yml validate -mp ~/Downloads/testing.csv -dt 'GenomicsAssay'```

and get this error: 

```
(scheamtic) ➜  temp schematic model -c ~/Desktop/temp/config.yml validate -mp ~/Downloads/testing.csv -dt 'GenomicsAssay'
Starting schematic...
The (model > input > location) argument with value '/Users/rallaway/desktop/temp/NF.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as /Users/rallaway/desktop/temp/NF.GenomicsAssay.schema.json
Traceback (most recent call last):
  File "/opt/miniconda3/envs/scheamtic/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/schematic/models/commands.py", line 169, in validate_manifest
    manifestPath=manifest_path, rootNode=data_type, jsonSchema=json_schema
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/schematic/models/metadata.py", line 251, in validateModelManifest
    errors, manifest = validate_all(self, errors, manifest, self.sg, jsonSchema)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/schematic/models/validate_manifest.py", line 187, in validate_all
    manifest, vmr_errors = vm.validate_manifest_rules(manifest, sg)
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/schematic/models/validate_manifest.py", line 157, in validate_manifest_rules
    self, validation_rules[0], manifest[col]
  File "/opt/miniconda3/envs/scheamtic/lib/python3.7/site-packages/schematic/models/validate_attribute.py", line 208, in list_validation
    invalid_entry=manifest_col[i]
NameError: name 'i' is not defined
```

If I then remove the last column (modelSystemName, which has `list` validation) from the manifest, I get this: 

```
(scheamtic) ➜  temp schematic model -c ~/Desktop/temp/config.yml validate -mp ~/Downloads/testing.csv -dt 'GenomicsAssay'
Starting schematic...
The (model > input > location) argument with value '/Users/rallaway/desktop/temp/NF.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as /Users/rallaway/desktop/temp/NF.GenomicsAssay.schema.json
Your manifest has been validated successfully. There are no errors in your manifest, and it can be submitted without any modifications.
```

**Comment by allaway** [comment]
I am going to transfer this issue to the `schematic` repository because, as you point out, this is a schematic issue probably.
